#### pi

In [ ]:
import math

# Print the value of pi
print ('pi = ', math.pi)

# Print the value of e
print ('e = ', math.e)

# Print the value of square root of 2
print ('sqrt(2) = ', math.sqrt(2))

#### mpmath库 高精度显示pi

In [ ]:
import mpmath as mp

mp.dps = 1000 + 1

print('print 1000 digits of pi behind decimal point')
print(mp.pi)

print('print 1000 digits of e behind decimal point')
print(mp.e)

print('print 1000 digits of sqrt(2) behind decimal point')
print(mp.sqrt(2))

#### 累加

In [9]:
import numpy as np

a_i = np.linspace(1,10,10)
print(a_i)

a_i_cumsum = np.cumsum(a_i)
print(a_i_cumsum)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  3.  6. 10. 15. 21. 28. 36. 45. 55.]


#### 转置

In [12]:
# row vector transposed to a column vector
a_row = np.array([[1, 2, 3]])

b = a_row.T

b_col = np.array([[1],[2],[3]])

a = b_col.T
a, b

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

#### 剪切

In [18]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_first_col = A[:,0] # saved as one dimension row

A_first_col_V2 = A[:,[0]] # saved as a column

A_first_second_col_V2 = A[:,[0,1]] # extract first and second columns

A_first_third_col_V2 = A[:,[0,2]] # extract first and third columns

A_first_row = A[[0],:] # extract first row

A_second_row = A[[1],:] # extract second row

A_second_row_first_col = A[[1],[0]] # i = 2, j = 1

In [23]:
A_first_col.shape, A_first_col

((2,), array([1, 4]))

In [22]:
A_first_col_V2.shape, A_first_col_V2

((2, 1),
 array([[1],
        [4]]))

In [25]:
A_first_second_col_V2.shape, A_first_second_col_V2

((2, 2),
 array([[1, 2],
        [4, 5]]))

In [26]:
A_first_third_col_V2.shape, A_first_third_col_V2

((2, 2),
 array([[1, 3],
        [4, 6]]))

In [33]:
A_first_row.shape, A_first_row

((1, 3), array([[1, 2, 3]]))

In [32]:
A_second_row.shape, A_second_row

((1, 3), array([[4, 5, 6]]))

In [35]:
A_second_row_first_col.shape, A_second_row_first_col

((1,), array([4]))

#### 矩阵加法  

In [44]:
list1=[1, 2, 3]
list2=[4, 5, 6]
print([x + y for x, y in zip(list1, list2)])
# zip() 打包成元组

print(list(map(lambda x,y:x+y, list1, list2)))
# map() 函数是一个内置函数，它用于对可迭代对象中的每个元素应用一个指定的函数，返回一个迭代器

x = np.array(list1)
y = np.array(list2)
print(x+y)

print(np.add(list1,list2))

[5, 7, 9]
[5, 7, 9]
[5 7 9]
[5 7 9]


In [39]:
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[1, 0, 0],
     [0, 1, 0]]

A_plus_B = [[A[i][j] + B[i][j]  
            for j in range(len(A[0]))] 
            for i in range(len(A))]

A_plus_B

[[2, 2, 3], [4, 6, 6]]

In [40]:
A = [[1, 2, 3],
     [4, 5, 6]]

B = [[1, 0, 0],
     [0, 1, 0]]

print(np.array(A) + np.array(B))

print(np.add(A, B))

[[2 2 3]
 [4 6 6]]
[[2 2 3]
 [4 6 6]]


DeltaGenerator()