#### 矩阵

In [1]:
# Bk4_Ch4_01.py

import numpy as np

# 2d matrix
A_matrix = np.matrix([[2,4],
                      [6,8]])
print(A_matrix.shape)
print(type(A_matrix))

# 1d array
A_1d = np.array([2,4])
print(A_1d.shape)
print(type(A_1d))

# 2d array
A_2d = np.array([[2,4],
                 [6,8]])
print(A_2d.shape)
print(type(A_2d))

# 3d array
A1 = [[2,4],
      [6,8]]

A2 = [[1,3],
      [5,7]]

A3 = [[1,0],
      [0,1]]
A_3d = np.array([A1,A2,A3])
print(A_3d.shape)
print(type(A_3d))

(2, 2)
<class 'numpy.matrix'>
(2,)
<class 'numpy.ndarray'>
(2, 2)
<class 'numpy.ndarray'>
(3, 2, 2)
<class 'numpy.ndarray'>


#### 对角线元素

In [14]:
# Bk4_Ch4_02.py

import numpy as np

A = np.matrix([[1,2,3],
              [4,5,6],
              [7,8,9]])

# extract diagonal elements
a = np.diag(A)

# construct a diagonal matrix
np.diag(a)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

#### 矩阵加法

In [15]:
# Bk4_Ch4_03.py

import numpy as np

# define matrix
A = np.matrix([[1, 2], [3, 4]])
B = np.matrix([[2, 6], [4, 8]])

# matrix addition
A_plus_B = np.add(A,B)
A_plus_B_2 = A + B


# matrix subtraction
A_minus_B = np.subtract(A,B)
A_minus_B_2 = A - B

A_plus_B, A_plus_B_2, A_minus_B, A_minus_B_2

(matrix([[ 3,  8],
         [ 7, 12]]),
 matrix([[ 3,  8],
         [ 7, 12]]),
 matrix([[-1, -4],
         [-1, -4]]),
 matrix([[-1, -4],
         [-1, -4]]))

#### 标量乘法

In [4]:
# Bk4_Ch4_04.py

import numpy as np

k = 2
X = [[1,2],
     [3,4]]

# scalar multiplication
k_times_X = np.dot(k,X)
k_times_X_2 = k*np.matrix(X)

#### 广播原则

In [16]:
# Bk4_Ch4_05.py

import numpy as np

# define matrix
A = np.matrix([[1, 2], 
               [3, 4],
               [5, 6]])

# scaler
k = 2;

# column vector c
c = np.array([[3],
              [2],
              [1]])

# row vector r
r = np.array([[2,1]])

# broadcasting principles

# matrix A plus scalar k
A_plus_k = A + k

# matrix A plus column vector c
A_plus_a = A + c

# matrix A plus row vector r
A_plus_r = A + r

# column vector c plus row vector r
c_plus_r = c + r

A_plus_k, A_plus_a, A_plus_r, c_plus_r

(matrix([[3, 4],
         [5, 6],
         [7, 8]]),
 matrix([[4, 5],
         [5, 6],
         [6, 7]]),
 matrix([[3, 3],
         [5, 5],
         [7, 7]]),
 array([[5, 4],
        [4, 3],
        [3, 2]]))

#### 标量乘法

In [17]:
# Bk4_Ch4_06.py

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 4],
              [1, 3]])

# matrix multiplication
A_times_B = np.matmul(A, B)
A_times_B_2 = A@B

A_times_B, A_times_B_2

(array([[ 4, 10],
        [10, 24]]),
 array([[ 4, 10],
        [10, 24]]))

#### 乘法例子 **

In [7]:
# Bk4_Ch4_07.py

import numpy as np

A = np.array([[1, 2]])

B = np.array([[5, 6], 
              [8, 9]])

print(A*B)

A = np.array([[1, 2]])

B = np.matrix([[5, 6], 
              [8, 9]])

print(A*B)

A = np.matrix([[1, 2]])

B = np.matrix([[5, 6], 
              [8, 9]])

print(A*B)

[[ 5 12]
 [ 8 18]]
[[21 24]]
[[21 24]]


#### 矩阵乘幂

In [18]:
# Bk4_Ch4_08.py

from numpy.linalg import matrix_power as pw

A = np.array([[1., 2.], 
              [3., 4.]])

# matrix inverse
A_3 = pw(A,3)
A_3_v3 = A@A@A

# piecewise power
A_3_piecewise = A**3

A_3, A_3_v3, A_3_piecewise

(array([[ 37.,  54.],
        [ 81., 118.]]),
 array([[ 37.,  54.],
        [ 81., 118.]]),
 array([[ 1.,  8.],
        [27., 64.]]))

In [9]:
# Bk4_Ch4_09.py

import numpy as np

A = np.matrix([[1,3],
               [2,4]])

print(A**2)

B = np.array([[1,3],
              [2,4]])

print(B**2)

[[ 7 15]
 [10 22]]
[[ 1  9]
 [ 4 16]]


#### 矩阵转置

In [10]:
# Bk4_Ch4_10.py

import numpy as np

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# matrix transpose
A_T = A.transpose()
A_T_2 = A.T

#### 矩阵的逆

In [19]:
# Bk4_Ch4_11.py

from numpy.linalg import inv
A = np.array([[1., 2.], 
              [3., 4.]])

# matrix inverse
A_inverse = inv(A)
A_times_A_inv = A@A_inverse

A_inverse, A_times_A_inv

(array([[-2. ,  1. ],
        [ 1.5, -0.5]]),
 array([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]]))

In [21]:
# Bk4_Ch4_12.py

import numpy as np

A = np.matrix([[1, 2], 
               [3, 4]])

print(A.I)

# B = np.array([[1, 2], 
#               [3, 4]])
# 
# print(B.I)

# 如果使用 np.matrix 创建矩阵，可以使用 .I 属性进行求逆操作；对于使用 np.array 创建的数组，应该使用 numpy.linalg.inv 函数

[[-2.   1. ]
 [ 1.5 -0.5]]


#### 迹

In [23]:
# Bk4_Ch4_13.py

import numpy as np
A = np.array([[1, -1, 0], 
              [3,  2, 4],
              [-2, 0, 3]])

# calculate trace of A
tr_A = np.trace(A)

tr_A

6

#### 逐项积

In [25]:
# Bk4_Ch4_14.py

import numpy as np

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

# Hadamard product
A_times_B_piecewise = np.multiply(A,B)
A_times_B_piecewise_V2 = A*B

A_times_B_piecewise, A_times_B_piecewise_V2

(array([[ 5, 12],
        [21, 32]]),
 array([[ 5, 12],
        [21, 32]]))

#### 行列式

In [ ]:
# Bk4_Ch4_15.py

import numpy as np
A = np.array([[4, 2], 
              [1, 3]])

# calculate determinant of A
det_A = np.linalg.det(A)