#### 矩阵乘法

In [2]:
# Bk4_Ch5_01.py

import numpy as np

a = np.array([[1],
              [2],
              [3]])

a_1D = np.array([1, 2, 3])

b = np.array([[-4],
              [-5],
              [-6]])

b_1D = np.array([-4, -5, -6])

# np.einsum() 爱因斯坦求和约定
print(np.einsum('ij->', a))
print(np.einsum('i->', a_1D))


6
6


In [3]:
print(np.einsum('ij,ij->ij', a, b))
print(np.einsum('i,i->i', a_1D, b_1D))


[[ -4]
 [-10]
 [-18]]
[ -4 -10 -18]


In [5]:
print(np.einsum('ij,ij->', a, b))
print(np.einsum('i,i->', a_1D, b_1D))


-32
-32


In [6]:
print(np.einsum('ij,ji->ij', a, a))
print(np.einsum('i,j->ij', a_1D, a_1D))


[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [7]:
print(np.einsum('ij,ji->ij', a, b))
print(np.einsum('i,j->ij', a_1D, b_1D))

[[ -4  -5  -6]
 [ -8 -10 -12]
 [-12 -15 -18]]
[[ -4  -5  -6]
 [ -8 -10 -12]
 [-12 -15 -18]]


In [8]:
# A is a square matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[-1, -4, -7],
              [-2, -5, -8],
              [-3, -6, -9]])

print(np.einsum('ji', A))


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
print(np.einsum('ij->', A))


45


In [10]:
print(np.einsum('ij->j', A))


[12 15 18]


In [11]:
print(np.einsum('ij->i', A))


[ 6 15 24]


In [12]:
print(np.einsum('ii->i', A))


[1 5 9]


In [13]:
print(np.einsum('ii->', A))


15


In [14]:
print(np.einsum('ij,jk->ik', A, B))


[[ -14  -32  -50]
 [ -32  -77 -122]
 [ -50 -122 -194]]


In [15]:
print(np.einsum('ij,jk->', A, B))


-693


In [16]:
print(np.einsum('ij,jk->ki', A, B))


[[ -14  -32  -50]
 [ -32  -77 -122]
 [ -50 -122 -194]]


In [17]:
print(np.einsum('ij,ij->ij', A, B))

[[ -1  -8 -21]
 [ -8 -25 -48]
 [-21 -48 -81]]
